// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLDskxbQLyZkkylyJy_K59snweq4bAbWA',
    appId: '1:669111875092:web:6483be85eac9ab57185901',
    messagingSenderId: '669111875092',
    projectId: 'mysavefood-4bfd6',
    authDomain: 'mysavefood-4bfd6.firebaseapp.com',
    storageBucket: 'mysavefood-4bfd6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASKMDAEFY6Am2181PXKQ6mTOSzvjK9WEM',
    appId: '1:669111875092:android:099e316c1bc222c9185901',
    messagingSenderId: '669111875092',
    projectId: 'mysavefood-4bfd6',
    storageBucket: 'mysavefood-4bfd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyuzDBQpHq9GSAMz0yhPG4c4hyZaQ1Lwg',
    appId: '1:669111875092:ios:4b7d54cc297379b3185901',
    messagingSenderId: '669111875092',
    projectId: 'mysavefood-4bfd6',
    storageBucket: 'mysavefood-4bfd6.firebasestorage.app',
    iosClientId: '669111875092-36fcqbp0tpoor649p7rcd8v67r8le08b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mysavefood',
  );
}
